NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls'))
]

news/urls.py
from django.urls import path
#имортируем созданное нами представление
from .views import NewsList, NewsDetail, NewsSearch, NewsCreate, NewsUpdate, NewsDelete, author_now, CategoryListView, \
    subscribe

urlpatterns = [
    path('', NewsList.as_view(), name='post_list'),
    path('search/', NewsSearch.as_view(), name='search'),
    path('<int:pk>/', NewsDetail.as_view(), name='post_detail'),
    path('create/', NewsCreate.as_view(), name='post_create'),
    path('<int:pk>/edit/', NewsUpdate.as_view(), name='post_edit'),
    path('<int:pk>/delete/', NewsDelete.as_view(), name='post_delete'),
    path('articles/create/', NewsCreate.as_view(), name='post_create'),
    path('articles/<int:pk>/edit/', NewsUpdate.as_view(), name='post_edit'),
    path('articles/<int:pk>/delete/', NewsDelete.as_view(), name='post_delete'),
    path('author_now/', author_now, name='author_now'),
    path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.urls import reverse


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def update_rating(self):
        posts_rating = self.posts.aggregate(pr=Coalesce(Sum('rating'), 0))['pr']
        comments_rating = self.user.comments.aggregate(cr=Coalesce(Sum('rating'), 0))['cr']
        posts_comments_rating = self.posts.aggregate(pcr=Coalesce(Sum('comment__rating'), 0))['pcr']

        self.rating = posts_rating * 3 + comments_rating + posts_comments_rating
        self.save()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    subscribers = models.ManyToManyField(User, blank=True, null=True, related_name='categories')

    def __str__(self):
        return self.name


class Post(models.Model):
    news = 'NE'
    article = 'AR'

    POST_TYPES = [
        (news, 'Новости'),
        (article, 'Статья')
    ]
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='posts')
    post_type = models.CharField(max_length=2, choices=POST_TYPES, default=news)
    post_time = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        if len(self.text) > 124:
            return self.text[:51] + '...'
        else:
            return self.text

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.title.title()}:{self.preview()}'


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.category.name


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    comment_time = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

templates/category_list.html
{% extends 'default.html'%}
{% load custom_filters %}
{% load custom_tags %}

<head>
    <meta charset="UTF-8">
    <title>News</title>
</head>
<body>
{% block content %}
    <h1>Все новости</h1>
    {% if is_not_author %}
    <button><a href="{% url 'author_now' %}">Стать автором</a> </button>
    {% endif %}
    {% if is_not_subscriber %}
        <p class="text-center"><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться на категорию</a></p>
    {% endif %}
    {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>
    <table>
        <tr>
            <td style='width:230px';><strong><u>Заголовок</u></strong></style></td>
            <td style='width:230px';><strong><u>Дата публикации</u></strong></style></td>
            <td style='width:200px';><strong><u>Содержание</u></strong></style></td>
            <td style='width:230px'><strong><u>Тип публикации</u></strong></td>
            <td style='width:230px';><strong><u>Категория</u></strong></style></td>
        </tr>
        {% for post in category_news_list %}
        <tr>
            <td>{{ post.title }}</td>
            <td>{{ post.post_time }}</td>
            <td>{{ post.text|truncatechars:21|censor }}</td>
            <td>{{ post.get_post_type_display }}</td>
            <td>
                {% for category in post.category.all %}
                <a href="{% url 'category_list' category.id %}">{{ category }}</a>
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </table>
{% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
{% endif %}

{% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
{% endif %}

{% endblock content%}
</body>

templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Здравствуйте! Новые статьи за последнюю неделю.</h2>
    <ul>
        {% for post in posts %}
            <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a> </li>
        {% endfor %}
    </ul>
</body>
</html>

templates/default.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Новостной портал</title>
        {% load static %}
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#">Новостной портал</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Link</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            <div class="text-center mt-10">
                <h1>News Portal</h1>
                <p class="lead"></p>
                <p>Версия 1.0</p>
            </div>
        </div>
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/post_create.html
{% extends 'default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Здравствуйте! Новая <a href="{{ link }}">статья</a> в избранном разделе.</h2>
        <p>{{ text }}</p>
</body>
</html>

templates/post_delete.html
{% extends 'default.html' %}

{% block content %}
<h1>Удаление новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/post_detail.html
{% extends 'default.html'%}
{% load custom_filters %}

<head>
    <meta charset="UTF-8">
    <title>News</title>
</head>
<body>
{% block content %}
    {% if need_subscribed %}
        <button><a href="{% url 'subscribe' post.id %}">Подписаться</a></button>
    {% endif %}
    <h1>Новость</h1>
{% if post %}
    <table>
        <tr>
            <td><u>Заголовок</u></td>
            <td><u>Содержание</u></td>
            <td><u>Дата публикации</u></td>
            <td><u>Категория</u></td>
        </tr>
        <tr>
            <td>{{ post.title }}</td>
            <td>{{ post.text|censor }}</td>
            <td>{{ post.post_time|date:'d M Y' }}</td>
            <td>
<!--            {% for category in post.category.all %}-->
                <a href="{% url 'category_list' category.id %}">{{ category }}</a>
                {% endfor %}
            </td>
            {% endif %}
        </tr>
    </table>

{% endblock content%}
</body>

templates/post_edit.html
{% extends 'default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/post_list.html
{% extends 'default.html'%}
{% load custom_filters %}
{% load custom_tags %}

<head>
    <meta charset="UTF-8">
    <title>News</title>
</head>
<body>
{% block content %}
    <h1>Все новости</h1>
    {% if is_not_author %}
    <button><a href="{% url 'author_now' %}">Стать автором</a> </button>
    {% endif %}
    {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>
    <table>
        <tr>
            <td style='width:230px';><strong><u>Заголовок</u></strong></style></td>
            <td style='width:230px';><strong><u>Дата публикации</u></strong></style></td>
            <td style='width:200px';><strong><u>Содержание</u></strong></style></td>
            <td style='width:200px';><strong><u>Тип публикации</u></strong></td>
            <td style='width:230px';><strong><u>Категория</u></strong></style></td>
        </tr>
        {% for post in posts %}
        <tr>
            <td>{{ post.title }}</td>
            <td>{{ post.post_time }}</td>
            <td>{{ post.text|truncatechars:21|censor }}</td>
            <td>{{ post.get_post_type_display }}</td>
            <td>
                {% for category in post.category.all %}
                <a href="{% url 'category_list' category.id %}">{{ category }}</a>
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </table>
{% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
{% endif %}

{% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
{% endif %}

{% endblock content%}
</body>

templates/search.html
{% extends 'default.html'%}
{% load custom_filters %}
{% load custom_tags %}

<head>
    <meta charset="UTF-8">
    <title>News</title>
</head>
<body>
{% block content %}
    <h1>Все новости</h1>
   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>
    <table>
        <tr>
            <td><u>Заголовок</u></td>
            <td><u>Дата публикации</u></td>
            <td><u>Содержание</u></td>
        </tr>
        {% for post in posts %}
        <tr>
            <td>{{ post.title }}</td>
            <td>{{ post.post_time }}</td>
            <td>{{ post.text|truncatechars:21|censor }}</td>
        </tr>
        {% endfor %}
    </table>
{% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
{% endif %}

{% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
{% endif %}

{% endblock content%}
</body>

templates/subscribe.html
{% extends 'default.html'%}

{% block content %}
    <h1 class="text-center">{{ message }} {{ category }}</h1>
{% endblock %}